OlympicMedalistBoard/Controllers/AthleteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OlympicMedalistBoard.BLL;
using OlympicMedalistBoard.Models;

namespace OlympicMedalistBoard.Controllers
{
    [Authorize]
    public class AthleteController : Controller
    {
        private readonly MedalService _medalService;
        private readonly SportService _sportService;
        private readonly CountryService _countryService;
        private readonly AthleteService _athleteService;
        private static string FILE_PATH = "";
        public AthleteController(AthleteService athleteService, SportService sportService, CountryService countryService, MedalService medalService)
        {
            _athleteService = athleteService;
            _sportService = sportService;
            _countryService = countryService;
            _medalService = medalService;
        }
        public IActionResult Index()
        {
            var athletes = _athleteService.GetAthletes();
            var athleteViewModels = athletes.Select(a => new AthleteViewModel
            {
                CountryID = a.CountryID,
                SportID = a.SportID,
                AthleteID = a.AthleteID,
                Name = a.Name,
                Birthdate = a.Birthdate,
                Country = a.Country,
                Sport = a.Sport,
                PhotoPath = GetPhotoPath(a)
            }).ToList();

            return View(athleteViewModels);
        }

        public IActionResult Create()
        {
            ViewBag.Sports = _sportService.GetSports();
            ViewBag.Countries = _countryService.GetCountries();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Athlete athlete, IFormFile? photo)
        {
            if (ModelState.IsValid)
            {
                Athlete newAthlete = _athleteService.AddAthlete(athlete);
                Upload(photo, newAthlete);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Invalid data");
            ViewBag.Sports = _sportService.GetSports();
            ViewBag.Countries = _countryService.GetCountries();
            return View(athlete);
        }

        public IActionResult Edit(int id)
        {
            var athlete = _athleteService.GetAthleteById(id);
            ViewBag.Sports = _sportService.GetSports();
            ViewBag.Countries = _countryService.GetCountries();
            var avm = new AthleteViewModel
            {
                CountryID = athlete.CountryID,
                SportID = athlete.SportID,
                AthleteID = athlete.AthleteID,
                Name = athlete.Name,
                Birthdate = athlete.Birthdate,
                Country = athlete.Country,
                Sport = athlete.Sport,
                PhotoPath = GetPhotoPath(athlete)
            };
            return View(avm);
        }

        [HttpPost]
        public IActionResult Edit(Athlete athlete, IFormFile? photo)
        {
            if (ModelState.IsValid)
            {
                Athlete newAthlete = _athleteService.UpdateAthlete(athlete);
                Upload(photo, newAthlete);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Invalid data");
            ViewBag.Sports = _sportService.GetSports();
            ViewBag.Countries = _countryService.GetCountries();
            return View(athlete);
        }

        public IActionResult Delete(int id)
        {
            var athlete = _athleteService.GetAthleteById(id);
            if (athlete != null)
            {
                AthleteViewModel viewModel = new AthleteViewModel();
                viewModel.Name = athlete.Name;
                viewModel.AthleteID = athlete.AthleteID;
                viewModel.PhotoPath = GetPhotoPath(athlete);
                return View(viewModel);
            }
            ModelState.AddModelError("", "Athlete not found");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(Athlete athlete)
        {
            if (athlete != null)
            {
                _athleteService.DeleteAthleteById(athlete.AthleteID);
                RemovePhoto(athlete);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Athlete not found");
            return RedirectToAction("Index");
        }

        private static string Upload(IFormFile file, Athlete athlete)
        {
            if (file != null && file.Length > 0)
            {
                var path = GetPhotoUploadPath(athlete);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }
                return path;
            }
            return string.Empty;
        }

        public static void RemovePhoto(Athlete athlete)
        {
            System.IO.File.Delete(GetPhotoUploadPath(athlete));
        }

        private static string GetPhotoUploadPath(Athlete athlete)
        {
            return Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", GetPhotoFileName(athlete));
        }

        public static string GetPhotoPath(Athlete athlete)
        {
            var photo = GetPhotoFileName(athlete);
            var photoPath = GetPhotoUploadPath(athlete);
            if (System.IO.File.Exists(photoPath))
            {
                return $"/img/{photo}?{new Random().NextDouble()}";
            }
            else
            {
                Console.WriteLine($"File not found: {photoPath}");
                return "/img/Athlete.jpg";
            }
        }

        public static string GetPhotoFileName(Athlete athlete)
        {
            return $"{athlete.AthleteID}-{athlete.Name}.jpg";
        }
    }
}

OlympicMedalistBoard/Controllers/CountryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OlympicMedalistBoard.BLL;
using OlympicMedalistBoard.Models;

namespace OlympicMedalistBoard.Controllers {
	[Authorize]
	public class CountryController : Controller {

		private readonly CountryService _countryService;
		public CountryController(CountryService countryService) {
			_countryService = countryService;
		}

		public IActionResult Index() {
			List<Country> countries = _countryService.GetCountries();
			return View(countries);
		}

		[HttpGet]
		public IActionResult Create() {
			return View();
		}

		[HttpPost]
		public IActionResult Create(CountryViewModel country) {
			if (ModelState.IsValid) {
				Country newCountry = new Country {
					CountryName = country.CountryName,
					CountryCode = country.CountryCode,
				};
				_countryService.AddCountry(newCountry);
				return RedirectToAction("Index");
			}
			return View(country);
		}

		[HttpGet]
		public IActionResult Update(int id) {
			var countryToEdit = _countryService.GetCountry(id);
			if (countryToEdit != null) {
				return View(countryToEdit);
			}
			return RedirectToAction("Index");
		}

		[HttpPost]
		public IActionResult Update(Country country) {
			if (ModelState.IsValid) {
				_countryService.UpdateCountry(country);
				return RedirectToAction("Index");
			}
			return View(country);
		}

		public IActionResult Delete(int id) {
			var country = _countryService.GetCountry(id);
			if (country != null) {
				return View(country);
			}
			return RedirectToAction("Index");
		}

		[HttpPost]
		public IActionResult ConfirmDelete(int CountryID) {
			var country = _countryService.GetCountry(CountryID);

			if (country != null) {
				_countryService.DeleteCountry(CountryID);
				return RedirectToAction("Index");
			}
			return RedirectToAction("Index");
		}
	}
}

OlympicMedalistBoard/Controllers/MedalController.cs
using Microsoft.AspNetCore.Mvc;
using OlympicMedalistBoard.BLL;
using OlympicMedalistBoard.Models;
using Microsoft.AspNetCore.Authorization;

namespace OlympicMedalistBoard.Controllers
{
    [Authorize]
    public class MedalController : Controller
    {
        private readonly MedalService _medalService;
        private readonly SportService _sportService;
        private readonly CountryService _countryService;
        private readonly AthleteService _athleteService;

        public MedalController(MedalService medalService, SportService sportService, CountryService countryService, AthleteService athleteService)
        {
            _medalService = medalService;
            _sportService = sportService;
            _countryService = countryService;
            _athleteService = athleteService;
        }

        public IActionResult Index()
        {
            var medals = _medalService.GetAllMedals();
            return View(medals);
        }

        [Authorize] 
        public IActionResult Details(int id)
        {
            var medal = _medalService.GetMedalById(id);
            if (medal == null)
            {
                return NotFound();
            }
            return View(medal);
        }

        [Authorize] 
        public IActionResult Create()
        {
            ViewBag.Sports = _sportService.GetSports();
            ViewBag.Countries = _countryService.GetCountries();
            ViewBag.Athletes = _athleteService.GetAthletes();
            return View();
        }

        [Authorize] 
        [HttpPost]
        public IActionResult Create(Medal medal)
        {
            if (ModelState.IsValid)
            {
                _medalService.AddMedal(medal);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Invalid data");
            ViewBag.Sports = _sportService.GetSports();
            ViewBag.Athlete = _athleteService.GetAthletes();
            return View(medal);
        }

        [Authorize] 
        public IActionResult Edit(int id)
        {
            var medal = _medalService.GetMedalById(id);
            ViewBag.Sports = _sportService.GetSports();
            ViewBag.Athlete = _athleteService.GetAthletes();
            return View(medal);
        }

        [Authorize] 
        [HttpPost]
        public IActionResult Edit(int id, Medal medal)
        {
            if (ModelState.IsValid)
            {
                medal.Sport = _sportService.GetSport(medal.SportID);
                medal.Athlete = _athleteService.GetAthleteById(medal.AthleteID);
                _medalService.UpdateMedal(medal);
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Invalid data");
            ViewBag.Sports = _sportService.GetSports();
            ViewBag.Athlete = _athleteService.GetAthletes();
            return View(medal);
        }

        [Authorize] 
        public IActionResult Delete(int id)
        {
            var medal = _medalService.GetMedalById(id);
            if (medal == null)
            {
                return NotFound();
            }
            return View(medal);
        }

        [Authorize] 
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            _medalService.DeleteMedal(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

OlympicMedalistBoard/Controllers/SportController.cs
using Microsoft.AspNetCore.Mvc;
//using Microsoft.AspNetCore.Authorization;**-
using OlympicMedalistBoard.Models;
using OlympicMedalistBoard.BLL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;


namespace OlympicMedalistBoard.Controllers
{
    [Authorize]
    public class SportController : Controller
    {
        //[Authorize]
        private readonly SportService _sportService;

        public SportController (SportService sportService)
        {
            _sportService = sportService;
        }
        //[Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            List<Sport> sports = _sportService.GetSports();
            return View(sports);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View(); 
        }

        [HttpPost]
        public IActionResult Create(SportViewModel sportViewModel)
        {
            if (ModelState.IsValid)
            {
                Sport newSport = new Sport()
                {
                    SportName = sportViewModel.SportName,
                };
                _sportService.AddSport(newSport);
                return RedirectToAction("Index");
            }
            return View(sportViewModel);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Sport sport = _sportService.GetSport(id);
            if (sport != null)
            {
                return View(new SportViewModel { SportID = sport.SportID, SportName = sport.SportName });
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Update(SportViewModel sportViewModel)
        {
            if (ModelState.IsValid)
            {
                Sport newSport = new Sport()
                {
                    SportID = sportViewModel.SportID,
                    SportName = sportViewModel.SportName
                };
                _sportService.UpdateSport(newSport);
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            Sport sport  = _sportService.GetSport(id);
            if (sport != null)
            {
                _sportService.DeleteSport(sport.SportID);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult ConfirmDelete(int SportID)
        {
            Sport sport = _sportService.GetSport(SportID);

            if (sport != null)
            {
                _sportService.DeleteSport(sport.SportID);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

    }
}

OlympicMedalistBoard/Views/Shared/_AthleteStyle.cshtml
@{
    var rand = new Random().NextDouble();
}
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<link rel="stylesheet" type="text/css" href="~/css/Athlete.css?@rand" />

OlympicMedalistBoard/Views/Shared/_Form.cshtml
@model dynamic
@*
    This partial view is used to render model atrributes into form fields.
    The model is defined as dynamic to allow the use of any model.
    It is a dynamic object that contains key-value pairs.
    Each key maps to an object with the following structure:
    FormData: dynamic
    {
        Key: {
            type: string,       // The type of the property (e.g., "text", "number").
            value: dynamic,     // The value of the property, which can be of any type.
            require: bool       // A boolean indicating whether the property is required.
        }
    }

*@
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@foreach(var prop in Model.GetType().GetProperties())
{
    var PropName = prop.Name;
    var PropValue = prop.GetValue(Model);
    var type = PropValue.type;
    var value = PropValue.value;
    var requireProperty = PropValue.GetType().GetProperty("require");
    var require = requireProperty != null ? (bool)requireProperty.GetValue(PropValue) : true;
    var requireString = require ? "required" : "";
    var warningString = $"{PropName} is required.";
    <div class="mb-2">
        @if (type == "hidden")
        {
            <input type="hidden" id="@PropName" name="@PropName" value="@value" />
        }
        else
        {
            @Html.Label((string)PropName, null, new { @class = "form-label" })
        }
        @if (type == "dropdown")
        {
            <select 
                id="@PropName" 
                name="@PropName" 
                class="form-control" 
                autocomplete="off" 
                data-val="@require.ToString().ToLower()" 
                data-val-required="@warningString" @requireString>
                <option value="">Select</option>
                @foreach (var item in (IEnumerable<SelectListItem>)value)
                {
                    <option 
                        value="@item.Value" 
                        selected="@(item.Selected ? "selected" : null)">
                        @item.Text
                    </option>
                }
            </select>
        }
        else if (type == "textarea")
        {
            <textarea 
                id="@PropName" 
                name="@PropName" 
                autocomplete="off" 
                class="form-control" 
                data-val="@require.ToString().ToLower()" 
            data-val-required="@warningString" @requireString>@value</textarea>
        }
        else if (type== "file")
        {
            <div class="d-flex justify-content-center">
                <script>
                    const openFile = () => {
                        const fileInput = document.querySelector("input[type='file']");
                        fileInput.onchange = (evt) => {
                            var reader = new FileReader();
                            reader.onload = function () {
                                var img = document.querySelector('.form-photo img');
                                img.src = reader.result;
                            };
                            reader.readAsDataURL(evt.target.files[0]);
                        };
                        fileInput.click();
                    };
                </script>
                <div class="col-3 form-photo position-relative border border-2 border-light p-1" role="button">
                    @if(value!=""){
                        <img src="@value" alt="" class="w-100" onclick="openFile();" />
                    }else{
                        <img src="~/img/Athlete.jpg" alt="" class="w-100" onclick="openFile();" />
                    }
                </div>
                <input type="file"
                    id="@PropName"
                    name="@PropName"
                    accept="image/*"
                    class="form-control d-none"
                    data-val="@require.ToString().ToLower()" 
                    data-val-required="@warningString" @requireString />
            </div>
        }
        else
        {
            <input
                type="@type" 
                id="@PropName" 
                name="@PropName" 
                value="@value" 
                autocomplete="off" 
                class="form-control" 
                data-val="@require.ToString().ToLower()" 
                data-val-required="@warningString"  @requireString/>
        }
        @Html.ValidationMessage((string)PropName, "", new { @class = "text-danger form-text" })
    </div> 
}

OlympicMedalistBoard/Views/Shared/_FormBtn.cshtml
@model string
<div class="d-flex mt-5 justify-content-center">
    <button type="submit" class="btn btn-outline-success sbtn">@Model</button>
    <a class="btn btn-outline-secondary sbtn mx-2" href="@Url.Action("Index")">Cancel</a>
</div>

OlympicMedalistBoard/Views/Shared/_FormViewForModels.cshtml
@model dynamic
@* 
    This partial view is used to render the form view for the models.
    It is used to render the form view for the models.
    The form view is rendered using the _Form partial view.
    The form buttons are rendered using the _FormBtn partial view.
    The model is defined as dynamic to allow the use of any model.
    The structure of the model is as follows:

        Model: dynamic
        {
            FormData: dynamic
            {
                Key: {
                    type: string,       // The type of the property (e.g., "text", "number").
                    value: dynamic,     // The value of the property, which can be of any type.
                    require: bool       // A boolean indicating whether the property is required.
                }
            },
            Btn: string                 // The name of the button.
        }

*@
<div class="d-flex justify-content-center w-100 ">
    @using (Html.BeginForm(FormMethod.Post,new { enctype = "multipart/form-data", @class = "w-50"}))
    {
        <partial name="_Form" model="@Model.FormData" />
        <partial name="_FormBtn" model="@Model.Btn" />
    }
</div>

OlympicMedalistBoard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OlympicMedalistBoard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OlympicMedalistBoard.styles.css" asp-append-version="true" />
    <partial name="_AthleteStyle.cshtml" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light mb-3 p-0">
            <div class="container position-relative">
                <a class="navbar-brand me-5" asp-area="" asp-controller="Home" asp-action="">
                    <img src="~/img/Paris2024.png" width="160" alt="logo" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between position-absolute w-100 start-0">
@*                     @if (User.Identity?.IsAuthenticated ?? false)
                    { *@
                        <div class="w-100">
                            <ul class="navbar-nav d-flex w-100 justify-content-center" style="gap:10px">

                                <li class="nav-item dropdown d-flex justify-content-center" style="width:18%">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="MedalDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Medal
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="MedalDropdown">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Medal" asp-action="">View All</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Medal" asp-action="Create">Add New</a></li>
                                    </ul>
                                </li>

                            <li class="nav-item dropdown d-flex justify-content-center" style="width:18%">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="AthleteDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Athlete
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="AthleteDropdown">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Athlete" asp-action="">View All</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Athlete" asp-action="Create">Add New</a></li>
                                    </ul>
                                </li>

                            <li class="nav-item dropdown d-flex justify-content-center opacity-0" style="width:18%">
                                    <a class="nav-link dropdown-toggle text-dark" href="/" role="button">
                                        Empty
                                    </a>
                            </li>

                            <li class="nav-item dropdown d-flex justify-content-center" style="width:18%">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="SportDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Sport
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="SportDropdown">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Sport" asp-action="">View All</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Sport" asp-action="Create">Add New</a></li>
                                    </ul>
                                </li>

                            <li class="nav-item dropdown d-flex justify-content-center" style="width:18%">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="CountryDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Country
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="CountryDropdown">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Country" asp-action="">View All</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Country" asp-action="Create">Add New</a></li>
                                    </ul>
                                </li>

                            </ul>

                        </div>

@*                     } *@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container d-flex justify-content-between">
            <span class="invisible" style="width:60px"></span>
            <partial name="_LoginPartial" />
            <span> &copy; 2024</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true" defer></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>